### PR TITLE
feat(docs):Upload ESV.pdf and KJV.pdf translations to backend folder

### PR DESCRIPTION
**Pull request by torok839098**
Dear Versify Team,
I had to individually upload the pdfs due to size. These include ESV and KJV translations. 

Thank you so much and God Bless you all!

### CODE REVIEW

**Comment by Namit2111** [comment]
what is this about?

**Comment by JustinhSE** [comment]
@Namit2111 this doesn't have relation to any issues

**Comment by torok839098** [comment]
Dear Bible Finder team, I want some clarification on how it's considered spam. This is my first year of joining Hacktoberfest as well as my first time learning about contribution to open source. I'm a career switcher from healthcare so the concepts of what is considered spam is still new to me. 
As I recall I saw this on your Discord: 

Welcome to the Bible Verse Finder! This repository contains code to parse and analyze the Bible. We want your help in adding features and improving this app! 

We are looking for contributors to work on  some of the following issues:

API integration - multiple bible translations
ML/Web Dev- make a Gemini Chatbot
Backend - User Authentication/Database integration
Convert the HTML to Next.js framework (need more people to help out here)

Let us know if you are interested!
---
So, perhaps I misread it. My thought process was that I decided to upload more pdfs of different versions of the bible which could be beneficial with the API or see how different versions show up for certain verses. Like you can look up key words and it shows up verses and it's labeled depending on the bible version. I would appreciate guidance on how to make it seem less 'spam' that way I understand for next projects and make my contributions to your project more useful.

Thank you so much!

**Comment by Namit2111** [comment]
Hi @torok839098  the issues with this PR were 
1. No issues was created before addressing this PR 
2. There was no discussion stating we need uploads of new books as PDF

**Pull request closed without merging**
