### PR TITLE
Feature/multiple bible translation

### PR DESCRIPTION
**Pull request by fortune710**
## Description
Created a feature to enable bible verse results for multiple translations to improve accessibility.

## Related Issues
This PR resolves issue #7

## Changes List
- [x] Created a centralized location for API implementation
- [x] Enabled API response caching for better performance
- [x] Refactored some code for better readability

## Type of Changes

- [x] Enhancement (improves or changes existing functionality)

## Checklist
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

## Output of My Changes
next-build
Screenshot 2024-10-19 095124
Screenshot 2024-10-19 095042
Screenshot 2024-10-19 094949

### CODE REVIEW

**Comment by fortune710** [comment]
@Namit2111 I couldn't squash the commits as it overwrote the entire commit history because of the merge changes that were made.

**Comment by JustinhSE** [comment]
@fortune710 for when a version is not available for a translation, is there a way to prevent a user from selecting it? Because for the first image it says it's unavailable for all

**Comment by fortune710** [comment]
@JustinhSE Unfortunately there's no way to know ahead of time what translations do not return results for certain bible verses

**Comment by Namit2111** [comment]
Why is their uncertainty?

**Comment by JustinhSE** [comment]
+1 to @Namit2111 comment. Fetches only have positive or negative responses. However, since we are about to move from 1 John, we are going to have to adjust this issue to individual verses having a more button so that you can individually either copy the verse or change that verse translation.

**Comment by JustinhSE** [comment]
But for now, only determine if the translation would be possible, if not do not display that translation name @fortune710

**Comment by JustinhSE** [comment]
@fortune710 the deadline for this issue to be eligible for a badge is coming up in the next few days. Feel free to work on this and open another PR

**Pull request closed without merging**
