### PR TITLE
changes made

### LINKED ISSUE #1: feat: Parse Entire Bible instead of John
### Overview 🤔 
We need to update the project to use the entire Bible for clustering instead of just 1 John. This will reduce the number of 0% similarity results.

### Task 🔧 
- Update the project to use the entire Bible for clustering to improve accuracy
- Reorganize the data storage for the Gutenberg Bible so that each book stores its own chapters, which in turn store their own scripture
- Modify the printing of the clusters to include the book name attached to the verse number (e.g., Matthew 5:38 instead of 5:38)
- Currently, we manually concatenate 1 John onto the verse, which needs to be removed

### PR DESCRIPTION
**Pull request by rabelmervin**
### **Description**

This PR updates the project to use the entire Bible for clustering, improving the accuracy and reducing the number of 0% similarity results. Additionally, the data storage has been reorganized, so each book stores its own chapters, which store their own scriptures. The printing of clusters now includes the book name with the verse number (e.g., Matthew 5:38), replacing the manual concatenation of 1 John.

###  Related Issues

Closes #1 (Bible clustering issue)

### Changes List

✅Updated the clustering to use the entire Bible instead of 1 John.

✅Reorganized data storage for the Gutenberg Bible, structuring by books, chapters, and scriptures.

✅ Modified cluster printing to include the book name attached to the verse number.

 ### Type of Changes

✅Bug fix (fixes an existing issue)

✅Enhancement (improves or changes existing functionality)

### Checklist

✅ My code follows the style guidelines of this project.

✅ I have performed a self-review of my code.

✅ I have commented my code, particularly in hard-to-understand areas.

✅ I have made corresponding changes to the issue .

✅My changes generate no new warnings.

✅ New and existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by Namit2111** [comment]
spam

**Comment by JustinhSE** [comment]
@Namit2111 this is not spam, he just followed something I asked, which was condense all the commits into 1

**Comment by JustinhSE** [comment]
@rabelmervin please however put what issue you closed by doing this PR so I can review it

**Comment by rabelmervin** [comment]
extremely sorry @Namit2111 @JustinhSE i made the changes in https://github.com/rabelmervin/bible-verse-finder/blob/bibleapp/backend/app.py  I also made a pr seperately to JustinhSE/bible-verse-finder

**Comment by JustinhSE** [comment]
No within the template of your pr put what issue it closes @rabelmervin

**Comment by Namit2111** [comment]
@rabelmervin check the whole directory you are updating app.py which is not where you should make changes, check the utils.py make your changes there

**Comment by JustinhSE** [comment]
@rabelmervin as namit said, do make changes only in util and not app.py

**Comment by rabelmervin** [comment]
Ok I'll make changes in utils.py @Namit2111 @JustinhSE.

**Comment by JustinhSE** [comment]
> Ok I'll make changes in utils.py @Namit2111 @JustinhSE.

Please open another PR and have the correct documentation including the # of the issue you are closing when you do complete that task

**Comment by rabelmervin** [comment]
Ok @JustinhSE have you seen the changes I made ?

**Pull request closed without merging**
