### PR TITLE
Updates:

### PR DESCRIPTION
**Pull request by AlexanderSanin**
1 Added error handling during initialization and request processing
2 Implemented caching for user input processing using @lru_cache
3 Separated logic into smaller, focused functions for better readability and maintainability
4 Added more detailed comments explaining each section of the code
5 Defined constants for frequently used values
6 Added input validation to handle empty user inputs
7 Optimized imports and model loading
8 Added docstrings to key functions

### CODE REVIEW

**Comment by AlexanderSanin** [comment]
@JustinhSE please rewiew and add a label "hacktoberfest-accepted"

**Comment by JustinhSE** [comment]
@AlexanderSanin please label what issue you are fixing in your PR text (or comment below)

**Comment by Namit2111** [comment]
Hey @AlexanderSanin  i appreciate you making these changes but these are not required as of now, please read the issue thread #2 to understand our requirements and do make a issue before creating another PR.

**Comment by AlexanderSanin** [comment]
> No clarification given.

@JustinhSE 
sorry, I'm new here. The purpose was to optimize the code, so please let me know if those updates aren't relevant, on what I can work on. Because you've marked my pr as spam, i've been disquialified from hacktoberfest and it's important to me

Please, remove that label, I can contribute to any meaningful PR needed

**Pull request closed without merging**
