### PR TITLE
feat:added techstack to about us

### LINKED ISSUE #24: Add Tech Stack Section to About Us Page
## Overview

We need to enhance our About Us page by including a dedicated section that showcases the tech stack used in our current project. This will help visitors and potential collaborators understand the technologies that power our application. 

### Task

1. **Review Project**: Go through our current project to identify all the technologies we are actively using. This includes programming languages, frameworks, libraries, tools, and any other relevant technologies.

2. **Curate List**: Create a concise and accurate list of these technologies. Ensure that only the technologies currently in use are included, removing any unused technologies.

3. **Design Section**: Based on the curated list, design a visually appealing section for the About Us page that highlights these technologies. Use the [Icon Cloud](https://magicui.design/docs/components/icon-cloud) to create engaging visuals.

4. **Implement Changes**: Update the About Us page to include the new tech stack section. Ensure that the section is responsive and maintains the overall design aesthetics of the page.

### PR DESCRIPTION
**Pull request by maiHydrogen**
## Description
Task
Review Project: Go through our current project to identify all the technologies we are actively using. This includes programming languages, frameworks, libraries, tools, and any other relevant technologies.

Curate List: Create a concise and accurate list of these technologies. Ensure that only the technologies currently in use are included, removing any unused technologies.

Design Section: Based on the curated list, design a visually appealing section for the About Us page that highlights these technologies. Use the [Icon Cloud](https://magicui.design/docs/components/icon-cloud) to create engaging visuals.

Implement Changes: Update the About Us page to include the new tech stack section. Ensure that the section is responsive and maintains the overall design aesthetics of the page. 

## Related Issues

- Closes #24 

## Changes List

- [ x]  added as section containing information about the techstack used in the project in the about us page which also includes a responsive icon cloud to represent techstack.
- this is current state -
Screenshot 2024-10-29 220800

## Type of Changes

- [ ] Bug fix (fixes an existing issue)
- [x] Enhancement (improves or changes existing functionality)
- [ ] Breaking change (introduces changes that break existing functionality)
- [ ] Documentation (adds or updates documentation)

## Checklist

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by JustinhSE** [comment]
@Namit2111

**Review by JustinhSE — CHANGES_REQUESTED** [review]
@maiHydrogen please remove committing  bin files

**Comment by JustinhSE** [comment]
Also add flask and python @maiHydrogen to the list of things (Python language and flask library)

**Comment by maiHydrogen** [comment]
> Also add flask and python @maiHydrogen to the list of things (Python language and flask library)

Flask is already in library and framework both and python will be added and bin files will be removed shortly. Any other changes regarding design or something??

**Comment by JustinhSE** [comment]
Looks good to go

**Comment by JustinhSE** [comment]
@maiHydrogen please run `npm run build` and fix all errors and submit another PR

**Comment by d-beloved** [comment]
Nice work @maiHydrogen, please in your PR fix, blur the background gradient like the other section.

**Comment by maiHydrogen** [comment]
> Nice work @maiHydrogen, please in your PR fix, blur the background gradient like the other section.

actually i asked them which one to choose from blurred and non-blurred one then Justin told me to keep this one so i kept this although you are right because blurred one will go along the theme set by the previous section.

**Comment by maiHydrogen** [comment]
> Looks good to go

@JustinhSE thanks for letting me work on this issue and also for your patience with this. i'll submit another PR with fixes soon and @d-beloved also a very big thanks for your help

**Comment by JustinhSE** [comment]
@maiHydrogen please fix your work tmrw so I can push it

**Comment by maiHydrogen** [comment]
> @maiHydrogen please fix your work tmrw so I can push it

can i do it till 2nd Nov noon/morning cause i have an exam in my uni on 1st Nov so i better study now u know i'm not that good there i hope you understand

**Comment by JustinhSE** [comment]
Yeah for sure!

**Comment by JustinhSE** [comment]
@maiHydrogen just looking for a status update

**Comment by maiHydrogen** [comment]
@JustinhSE
solved all errors in npm-run-build anything else or i raise a PR like d=beloved said that we should blur the background or leave it as it is?? 
Screenshot 2024-11-03 072141

**Comment by JustinhSE** [comment]
Right now, leave it as it is and just open a pr so I can merge it @maiHydrogen

**Pull request merged**
