### PR TITLE
Chatbot RAG pipeline

### PR DESCRIPTION
**Pull request by amannaik247**
I have added a chatbot folder and a Bible_pdfs folder:

Bible pdfs folder:
Add any bible files you want here which will be embedded

Chatbot folder:
This contains a qdrantdb file which has functions to vectorise the documents in the pdfs folder, which will then be stored in a Qdrantdb as embeddings (Used Google Gemini for creating embeddings).

The rag.py file has functions for retrieval of any information of the documents using Groq chat api which gives response to any user questions(The groq chatbot is using llama3.1-70b model)
Later on when the ui is set you can use flask to easily set up an endpoint to this rag since all the responses from this rag file will be in Json format(dictionary). 
The final response from this rag.py file will be answer to the user question along with the context from the document provided.
Please go through the files and do update me if you need any further help.

Following is the response generated for the question("How was Jesus born?):
image

### CODE REVIEW

**Comment by Namit2111** [comment]
Hi! Please brief the rate limit of groq also, process to run this step by step, how many times it will need to initialize

**Comment by amannaik247** [comment]
The free tier of Groq allows for 14,400 requests per day and 6,000 tokens per minute.

First of all you will need to set up the .env file and install the requirements_chatbot.txt file.
image

Step1:
Setup: The above image contains a Qdrantdb api key name and qdrantdb url which you can get by creating a free cluster on the https://cloud.qdrant.io/ website.
Also create a google ai api key https://aistudio.google.com/app/apikey
Create a Groq account and then create a API key on https://console.groq.com/keys

Step 2: 
Setting up the collection and data embedding can be done by just running the "qdrantdb.py" file.
Once this file has ran you will see a successful message on our terminal (Please run in the bible-app directory)
Outcome: This will result in a vectordb in Qdrant which you can check out in the qdrant db dashboard on the same website and success message on the terminal.

Step 3: 
To get response from the chatbot using Groq you have to run the rag.py file as a module ( you can hardcode your question on line 56)
Code for the same: in terminal:
python -m chatbot.rag 
Outcome: A dictionary containing the answer and a context string from where it got the answer in pdf. 
image

**Comment by Namit2111** [comment]
What is the need of google api key?

**Comment by amannaik247** [comment]
https://www.youtube.com/watch?v=mHrwS6ZoNKc
I you need help setting up the qdrant api and url you can follow this tutorial untill 2:00 since creating a collection is coded into the files itself.

**Comment by Namit2111** [comment]
> What is the need of google api key?

Hey @amannaik247 please clarify this too

**Comment by amannaik247** [comment]
> What is the need of google api key?

When running the qdrantdb.py file for creating "embeddings of the documents" i am using googlegenerativeai embeddings.
But for writing the response in rag.py i am using the Groq api.

**Comment by Namit2111** [comment]
> > What is the need of google api key?
> 
> When running the qdrantdb.py file for creating "embeddings of the documents" i am using googlegenerativeai embeddings. But for writing the response in rag.py i am using the Groq api.

Do generating embeddings require google key?

**Comment by amannaik247** [comment]
> > > What is the need of google api key?
> > 
> > 
> > When running the qdrantdb.py file for creating "embeddings of the documents" i am using googlegenerativeai embeddings. But for writing the response in rag.py i am using the Groq api.
> 
> Do generating embeddings require google key?

yes, creating an embedding and retrieving information through embedding will require google api key and it is free so there is no problem .

**Comment by Namit2111** [comment]
Ok 👌

**Pull request merged**
