### PR TITLE
Feat/about us page

### LINKED ISSUE #23: Add "About Us" Section with Dynamic Stats
## Overview
We aim to enhance our website by incorporating a new "About Us" section. This section will feature dynamic statistics that reflect the vibrancy and activity of our project. The statistics to be displayed include:

- Number of contributors
- Number of lines of code
- Number of commits

These stats should be automatically updated by connecting them to our GitHub repository, ensuring real-time accuracy. For the implementation, we recommend using the Number Ticker component from Magic UI, as detailed in the documentation: [Magic UI Number Ticker](https://magicui.design/docs/components/number-ticker).

### Task
1. Develop and integrate an "About Us" section (use routing in `Next.js`).
2. Implement the Number Ticker component to display the following statistics:
   - Total number of contributors
   - Total number of lines of code
   - Total number of commits
3. Establish a connection with our GitHub repository to ensure the statistics are dynamically updated.
4. Test the functionality to confirm the accuracy and responsiveness of the stats display.

---

**Note:** If you require assistance or have ideas for additional statistics or other enhancements, please contribute to the discussion thread below. Your input is valuable to us!

### PR DESCRIPTION
**Pull request by d-beloved**
Screenshot 2024-10-28 at 14 51 09

## Description
This PR adds the About Us page to the app, showing the "Number of commits in the repo", "total number of contributors", and the "lines of code"

## Related Issues

- Closes #23  (issue)

## Changes List

- [x] Adds the "about" route
- [x] Creates functions to get the statistics from the GitHub REST API
- [x] Makes the About us page responsive
- [x] Add a button to star the repository on GitHub  

## Type of Changes

- [x] Enhancement

## Checklist

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by d-beloved** [comment]
@Namit2111 and @JustinhSE this PR is up for review.

@Namit2111 please help check what the error is on Vercel. I have run `npm run build` for the production build on my terminal, and everything runs smoothly. Vercel is likely catching another issue online.
Screenshot 2024-10-28 at 15 40 20

**Comment by JustinhSE** [comment]
@d-beloved can you cd outside of the about us section and run `npm run build` in the frontend directory just to make sure?

**Comment by d-beloved** [comment]
> @d-beloved can you cd outside of the about us section and run `npm run build` in the frontend directory just to make sure?

I've done that @JustinhSE it builds without errors on the main branch.

**Comment by JustinhSE** [comment]
Okay great, Namit needs to review it so it can be merged

**Comment by Namit2111** [comment]
hey @d-beloved Can you make a Readme.md in frontend folder explaining the current working structure of the app!?

**Comment by d-beloved** [comment]
> hey @d-beloved Can you make a Readme.md in frontend folder explaining the current working structure of the app!?

I will add the Readme after the second About Us issue (#24)  has been done

**Pull request merged**
